umicro/uView2.0

- uni_modules/uview-ui/components/u-album/u-album.vue
> fix: 修复album组件在H5单张图片不能正确显示的问题

- uni_modules/uview-ui/components/u-image/u-image.vue
> fix: 修复u-image报borderRadius未找到的异常

- uni_modules/uview-ui/components/u-toast/u-toast.vue
> fix: u-toast设置loading=true不生效

- uni_modules/uview-ui/components/u-toast/u-toast.vue
> fix: u-toast组件的icon属性配置不生效

- pages/componentsC/indexList/indexList.nvue
- uni_modules/uview-ui/components/u-index-anchor/u-index-anchor.vue
- uni_modules/uview-ui/components/u-index-list/u-index-list.vue
修改了u-index-list,u-index-anchor组件源码，以及indexList示例代码，让u-index-list组件支持更多的字符，已在微信小程序，h5,手机模拟器上测试过，一切正常
> 优化u-index-list组件，使其支持更多的字符

- uni_modules/uview-ui/components/u-swiper/u-swiper.vue
- uni_modules/uview-ui/components/u-tag/u-tag.vue
**PS: 先测试一下**。
1. 修复tag组件 type值info不生效问题
2. 修复Swiper组件radius在ios端vue页面无效Android端nvue页面无效
> fix: 修复tag组件和swiper组件问题

- uni_modules/uview-ui/components/u-upload/utils.js
修复u-upload组件报value is not defined且无法正常使用的错误
> 修复u-upload组件报value is not defined的错误

- uni_modules/uview-ui/libs/util/async-validator.js
> fix: 修改整形和浮点数的验证逻辑，从原先的数学验证法改为正则验证法，以期字符串类型的数字能通过验证

- uni_modules/uview-ui/components/u-checkbox/u-checkbox.vue
变动：
1. 新增watch checked，修复ischecked不随props.checked变动变化，为了实现全选/取消全选
> fix(checbox): 修复ischecked不更新

- uni_modules/uview-ui/components/u-steps-item/u-steps-item.vue
修复内容：
1. 解决column的竖线飘逸
2. 解决vue情况下没有边框
文档id#37
> fix(steps): 样式修复 #180

- uni_modules/uview-ui/components/u-tabs/u-tabs.vue
> fix: lineWidth传入带单位的字符串的时候偏移量计算错误(NaN)问题

- uni_modules/uview-ui/components/u-picker/u-picker.vue
> fix: item-height单位导致样式问题

- uni_modules/uview-ui/components/u-swipe-action-item/u-swipe-action-item.vue
> fix:微信小程序端无法上下滑动

- uni_modules/uview-ui/components/u-divider/u-divider.vue
- uni_modules/uview-ui/组件/u 型分隔线/u-divider.vue
> fix: 修复divider组件click事件无效问题

- uni_modules/uview-ui/components/u-divider/u-divider.vue
> Revert "fix: 修复divider组件click事件无效问题"

- pages/componentsB/countDown/countDown.nvue
> fix manual seting bug for countDown.nvue

- uni_modules/uview-ui/components/u-slider/props.js
- uni_modules/uview-ui/components/u-slider/u-slider.vue
- uni_modules/uview-ui/libs/config/props/slider.js
> fix:slider组件添加disabled属性

- uni_modules/uview-ui/components/u-image/u-image.vue
> fix: 1. 修复图片地址赋值后判断加载状态为完成问题

- pages/componentsC/calendar/calendar.nvue
- uni_modules/uview-ui/components/u-calendar/month.vue
- uni_modules/uview-ui/components/u-calendar/u-calendar.vue
> fix:修复日历滚动到默认日期月份的功能

- pages/componentsB/search/search.nvue
- uni_modules/uview-ui/components/u-search/u-search.vue
feature:(u-search) 添加左侧图标点击事件 click-icon
> feat(u-search): 添加左侧图标点击事件 click-icon

- uni_modules/uview-ui/components/u-code-input/u-code-input.vue
> fix(u-code-input): 修复输入框没有往左移出一半屏幕

- uni_modules/uview-ui/components/u-upload/utils.js
> fix: upload组件在accept=all的时候没有作用

- uni_modules/uview-ui/components/u-image/u-image.vue
> Revert "fix: 1. 修复图片地址赋值后判断加载状态为完成问题"

- uni_modules/uview-ui/components/u-icon/u-icon.vue
preventDefault不在uni.$u上，而是被全局混入的
close #142
> fix: u-icon添加stop属性的时候报错

- uni_modules/uview-ui/components/u-image/u-image.vue
https://github.com/umicro/uView2.0/issues/146#issue-1074040641
> fix: u-image slot 加载和错误的图片失去了高度

- uni_modules/uview-ui/components/u-index-list/u-index-list.vue
> fix: u-index-list中footer插槽与header插槽存在性判断错误

- uni_modules/uview-ui/components/u-image/u-image.vue
> fix: u-image在App-Nvue真机调试下失去高度

- pages/componentsB/search/search.nvue
修复 search 组件文档点击左侧按钮没有出现 toast 反馈的问题
> docs(u-search): 修复 search 组件文档点击左侧按钮没有出现 toast 反馈的问题

- uni_modules/uview-ui/components/u-text/u-text.vue
- uni_modules/uview-ui/libs/css/common.scss
> fix: u-lines

- uni_modules/uview-ui/libs/function/index.js
> fix: 修复传入字符串时间戳时timeFormat解析为NaN (fix #208)

- uni_modules/uview-ui/components/u-form-item/props.js
- uni_modules/uview-ui/components/u-form-item/u-form-item.vue
- uni_modules/uview-ui/libs/config/props/formItem.js
> 修复form-item在添加leftIcon属性后报leftIconStyle未定义的错误

- pages/example/components.nvue
- uni_modules/uview-ui/libs/function/digit.js
- uni_modules/uview-ui/libs/function/index.js
> 修复priceFormat的精度问题

- uni_modules/uview-ui/components/u-image/u-image.vue
fix：修复`u-image`组件`loading`无效果的问题
> fix：修复`u-image`组件`loading`无效果的问题

- uni_modules/uview-ui/components/u--text/u--text.vue
修复u--text组件设置`decoration`属性未生效的问题
> 修复u--text组件设置`decoration`属性未生效的问题

- uni_modules/uview-ui/components/u-text/u-text.vue
- uni_modules/uview-ui/components/u-text/value.js
> fix:修复只有手机号可拨打

- uni_modules/uview-ui/components/u-upload/u-upload.vue
调起API的时候检查用户传入的类型，如果是字符串则做单独处理
> fix: upload的capture传入字符串的时候不生效

- uni_modules/uview-ui/components/u-upload/u-upload.vue
> fix:修复`upload`组件条件编译位置判断错误，导致`previewImage`属性设置为`false`时，整个组件都会被隐藏的问题

- uni_modules/uview-ui/components/u-code-input/u-code-input.vue
feat(u-code-input): 添加输入时光标效果动画，优化用户体验（不加光标效果不知道输入的位置，体验不是很好）
效果如下：
> feat(u-code-input): 添加输入时光标效果动画

- uni_modules/uview-ui/components/u-code-input/u-code-input.vue
bugfix: 修复`u-code-input`组件在`nvue`页面编译到`app`平台上光标异常问题（app去除此功能）
优化在得到光标时才会显示
> bugfix: 修复u-code-input组件在nvue页面编译到app平台上光标异常问题（app去除此功能）

- uni_modules/uview-ui/components/u-code-input/props.js
- uni_modules/uview-ui/components/u-code-input/u-code-input.vue
- uni_modules/uview-ui/libs/config/props/codeInput.js
Signed-off-by: byakkili <lgn_19930923@163.com>
> feat(u-code-input): 添加 键盘弹起时，是否自动上推页面参数：adjustPosition

- pages/componentsA/loading-page/loading-page.nvue
- uni_modules/uview-ui/components/u-loading-page/props.js
- uni_modules/uview-ui/components/u-loading-page/u-loading-page.vue
- uni_modules/uview-ui/libs/config/props/loadingPage.js
添加控制图标大小的属性 iconSize. 解决 issue #561
> feat(u-loading-page): 添加控制图标大小的属性 iconSize. (resolved #561)

- pages/componentsC/loadmore/loadmore.nvue
- uni_modules/uview-ui/components/u-line/props.js
- uni_modules/uview-ui/components/u-loadmore/props.js
- uni_modules/uview-ui/components/u-loadmore/u-loadmore.vue
- uni_modules/uview-ui/libs/config/props/loadmore.js
修改代码文件：uni_modules/uview-ui/components/u-loadmore
修改内容：修改loadmore组件中的线条为可自定义颜色、虚/实线
修改示例文件：pages/componentsC/loadmore
修改示例内容：新增案例添加 lineColor 和 dashed 进行测试。
修改结果：测试有效
> fix：loadmore组件中的线条为可自定义颜色、虚/实线

- uni_modules/uview-ui/components/u--input/u--input.vue
- uni_modules/uview-ui/components/u--textarea/u--textarea.vue
- uni_modules/uview-ui/components/u-input/props.js
- uni_modules/uview-ui/components/u-input/u-input.vue
- uni_modules/uview-ui/components/u-textarea/props.js
- uni_modules/uview-ui/components/u-textarea/u-textarea.vue
[support ignoreCompositionEvent](https://gitee.com/dcloud/unidocs-zh/commit/4cf55edcc2e9588be443000434c11e5feb72e224)
> feat: [input/textarea] add ignoreCompositionEvent

- uni_modules/uview-ui/libs/function/test.js
根据工信部发布的《电信网编号计划（2017年版）》进行修改。  
https://www.miit.gov.cn/zwgk/zcwj/wjfb/txy/art/2020/art_eea7322361dc4a3e832a51ba751ecb00.html
> refactor: 优化验证手机格式的正则

- uni_modules/uview-ui/components/u-form-item/props.js
- uni_modules/uview-ui/components/u-form-item/u-form-item.vue
- uni_modules/uview-ui/libs/config/props/formItem.js
给 form-item 添加 labelPosition 属性，缺省时以 form 设置为准
https://github.com/umicro/uView2.0/issues/96
https://github.com/umicro/uView2.0/issues/735
> fix:form-item添加labelPosition属性

- uni_modules/uview-ui/components/u-input/u-input.vue
fix 在 app 端，u-input 组件的 password 属性在动态切换为 false 时失效的问题 #868 。
> fix: input switch password

- uni_modules/uview-ui/components/u-button/u-button.vue
> feat(button): 添加用户同意隐私协议事件回调

- uni_modules/uview-ui/components/u-picker/u-picker.vue
fixes #698 
fixes #954 
fixes #953 
fixes #716 
fixes #673
> fix: alipayapp `picker` style

- uni_modules/uview-ui/components/u-tabs/u-tabs.vue
tabs增加长按事件支持，关闭[#1021 ](https://github.com/umicro/uView2.0/issues/1021)
> feat:tabs增加长按事件支持

- uni_modules/uview-ui/components/u-datetime-picker/u-datetime-picker.vue
- uni_modules/uview-ui/components/u-picker/u-picker.vue
bug单如下： #424 #980 #481 
复现也可以参考上方bug单
修复后已经不报错，并功能正常
> 修复抖音小程序u-datetime-picker报错问题

- uni_modules/uview-ui/components/u-image/u-image.vue
> fix：修复u-image组件bgColor属性不生效的问题

- uni_modules/uview-ui/components/u-datetime-picker/props.js
- uni_modules/uview-ui/components/u-datetime-picker/u-datetime-picker.vue
- uni_modules/uview-ui/libs/config/props/datetimePicker.js
fix:https://github.com/umicro/uView2.0/issues/991#issue-1877081536
同时希望把这个pr也合掉
https://github.com/umicro/uView2.0/pull/803
> feat：datetime-picker支持immediateChange属性

- uni_modules/uview-ui/components/u-popup/u-popup.vue
> fix(u-popup): 设置duration为字符串值时，遮罩的打开、关闭很缓慢
