umicro/uView2.0

uni_modules/uview-ui/components/u-text/u-text.vue

修复u-text组件 price 模式 ￥符号没有继承 模式颜色

fix:u-text mode price text not extend type color

---

uni_modules/uview-ui/components/u-picker/u-picker.vue

处理undefined的情况，将原有的this.lastIndex[i]更改为(this.lastIndex[i] || 0)

fix: 当picker组件的lastIndex数组为空数组的时候无法正确判断当前变化的列

---

uni_modules/uview-ui/components/u-number-box/u-number-box.vue

在onFocus和emitChange中补上name参数
close #133

fix: numberBox的事件中不包含name参数

---

pages/componentsC/indexList/indexList.nvue
uni_modules/uview-ui/components/u-index-anchor/u-index-anchor.vue
uni_modules/uview-ui/components/u-index-list/u-index-list.vue

给u-index-list的indexList添加了_符号，使用#代替_页面展示，但id处是以_展示，最终使其支持#符号

完善u-index-list，使其默认支持#符号

---

uni_modules/uview-ui/components/u-text/value.js

修改用来进行校验的正则表达式，Github历史文件比对有误，实际修改的为14行至16行

fix: u-text金额模式传0报错

---

uni_modules/uview-ui/components/u-avatar/u-avatar.vue

打包app、H5时候 提示 文件查找失败:'uni-view/components/open-data' open-data不支持app和h5

fix: 修复u-avatar 导致打包app、H5时候报错

---

uni_modules/uview-ui/libs/config/props/input.js

此为小程序的原生input的问题，当传的值为空字符串的时候占位符显示为一个true。解决方案为显式的给null。

fix: input的placeholder在小程序端默认显示为true

---

uni_modules/uview-ui/components/u-code-input/u-code-input.vue

问题如下：
```html
<u-code-input
maxlength="5" // 显示异常，只显示一个输入格
value="46821"
></u-code-input>
```
```html
<u-code-input
:maxlength="5" // 显示正常
value="46821"
></u-code-input>
```

fix(u-code-input): 修复 maxlength 属性值为 String 类型时显示异常

---

uni_modules/uview-ui/components/u-index-list/u-index-list.vue

主要修改两个部分
1. 给scroll-view的style的height修改成了maxHeight
2. this.scrollViewHeight = this.sys.windowHeight - this.customNavHeight，使scroll-view的最大高度不会影响navbar和tabbar

解决u-index-list组件设置在tabbar页面，填充内容较少时，scroll-view仍能滚动问题

---

uni_modules/uview-ui/components/u-form/u-form.vue

fix(u-form): 修复clearValidate方法不生效

---

uni_modules/uview-ui/components/u-tabbar/u-tabbar.vue

之前的源代码中placeholder的高度是写死的50，如果开启了safeAreaInsetBottom，这个高度是不准确的，

修复微信小程序环境中tabbar组件开启safeAreaInsetBottom属性后，placeholder高度填充不正确

---

uni_modules/uview-ui/components/u-swiper/u-swiper.vue

作为props传入的current和组件实际使用的currentIndex未关联初始值导致的问题。
close #139

fix: swiper在current指定非0时缩放有误

---

uni_modules/uview-ui/libs/function/index.js

1.15 * 100 = 114.99999...，同样出现问题的还有1.12，1.13, 1.14等等
正如0.1 + 0.2 = 0.30000000000000004，但(1+2)/10 = 0.3一样，可以使用同样的思路适当的把数量级跳高来规避精度问题
即 1. 15 * 1000 / 10 = 115 
close #348

fix：修复priceFormat在部分情况下出现精度损失问题

---

uni_modules/uview-ui/libs/function/index.js

在Safari/Webkit中，new Date仅支持/作为分割符的字符串时间

feat: timeFormat兼容在Safari/Webkit平台传入-分割的字符串时间

---

uni_modules/uview-ui/components/u-search/props.js
uni_modules/uview-ui/components/u-search/u-search.vue
uni_modules/uview-ui/libs/config/props/search.js

在配置uni.$u.config.unit="rpx"后搜索组件的icon尺寸变得过小，其原因是写死的数值22

fix: 在unit为rpx后搜索组件内置的搜索图标尺寸不正常

---

uni_modules/uview-ui/components/u-tabs/u-tabs.vue

修复scrollable设置为false后没有改变tab-item为flex:1平分样式

fix: u-tabs禁止滚动情况下没有平分tabItem样式

---

uni_modules/uview-ui/components/u-navbar/u-navbar.vue

修复`config.unit`属性设为`rpx`时，导航栏占用高度不足导致塌陷的问题

fix：修复`config.unit`属性设为`rpx`时，导航栏占用高度不足导致塌陷的问题

---

uni_modules/uview-ui/libs/mixin/mixin.js

fix:修复mixin中bem方法生成的类名在支付宝和字节小程序中失效

---

uni_modules/uview-ui/components/u-swiper-indicator/u-swiper-indicator.vue

fix 修复已设置单位 uni.$u.config.unit = 'rpx'时，线型指示器 transform 的位置翻倍，导致指示器超出宽度问题

fix: 修复已设置单位 uni..config.unit = 'rpx'时，线型指示器 transform 的位置翻倍，导致指示器超出宽度

---

uni_modules/uview-ui/components/u-datetime-picker/u-datetime-picker.vue

如果当前选中的日期为3月31日，此时将月份选中成2月时，索引会更新成3月3日

fix: 修复时间选择器索引不正确问题

---

pages/componentsC/tabs/tabs.nvue
uni_modules/uview-ui/components/u-tabs/props.js
uni_modules/uview-ui/components/u-tabs/u-tabs.vue
uni_modules/uview-ui/libs/config/props/tabs.js

业务需求中，u-tabs 中滑块会有需要设置成例如“弧形”这样的形状图，这个目前无法通过API去设置背景图，当前可以通过设置lineColor为透明，再借助css设置滑块的背景图达到目的，为了开发方便，遂将 "lineColor" 设置的 "backgroundColor" 调整为 "background", 并 "Props" 增加 “lineBgSize” 属性设置 “backgroundSize”。

feat: u-tabs 组件支持设置滑块背景图

---

uni_modules/uview-ui/components/u-button/u-button.vue

修复 u-button 中 loadingSize 设置无效 #538

fix(button): 修复 loadingSize 设置无效

---

pages/componentsC/loadmore/loadmore.nvue
uni_modules/uview-ui/components/u-loadmore/props.js
uni_modules/uview-ui/components/u-loadmore/u-loadmore.vue
uni_modules/uview-ui/libs/config/props/loadmore.js

修改代码文件：uni_modules/uview-ui/components/u-loadmore
修改内容：修改loadmore组件中的加载图标由之前的固定大小 17 改为添加 iconSize 属性来自定义图标大小以满足更多需求。
修改示例文件：pages/componentsC/loadmore
修改示例内容：修改基本使用案例添加 iconSize 进行测试。
修改结果：测试有效

fix：修改loadmore组件中的加载图标由之前的固定大小 17 改为添加 iconSize 属性来自定义图标大小以满足更多需求

---

uni_modules/uview-ui/components/u-picker/props.js
uni_modules/uview-ui/components/u-picker/u-picker.vue
uni_modules/uview-ui/libs/config/props/picker.js

singleIndex在源码中没有任何引用，且已经提供defaultIndex作为各列的默认索引，单列选择器同样可以使用，所以singleIndex参数无实际用途。已在文档提交pr13删除对应部分。

fix:删除无用参数singleIndex

---

uni_modules/uview-ui/components/u-radio/u-radio.vue

发现问题：从1.0迁移至2.0发现部分radio表现异常，插槽内容没有显示。
研究：对比uview1.0代码发现1.0是有一个默认插槽用于修改label内容。2.0却更改为只有icon插槽。
结论：现2.0radio只有一个icon的具名插槽，对于自定义样式的话显然是不够的，但是这个功能又确实蛮需要。目前自己暂时改了uni_moudels里的代码。
考虑到别人可能也会遇到类似问题，并本着希望uview越来越好的想法，故提出此pr。

radio增加一个默认插槽用于自定义修改label内容

---

uni_modules/uview-ui/libs/function/index.js

在 Safari 中格式化出错
```js
uni.$u.timeFormat('2022-07-10T01:02:03')
// "NaN-NaN-NaN"
```

fix(timeFormat): Safari中格式化'2022-07-10T01:02:03'出错

---

uni_modules/uview-ui/components/u--form/u--form.vue

解决在表单校验中，trigger参数写‘blur’时，输入文字会触发校验的bug

修复u--form组件BUG，表单校验trigger触发器参数无效问题

---

uni_modules/uview-ui/components/u-avatar/u-avatar.vue

设置overflow:hidden，用于超出隐藏。
修复[#1027 ](https://github.com/umicro/uView2.0/issues/1027)

fix: 修复square属性在小程序open-data下无效问题

---

pages/componentsC/datetimePicker/datetimePicker.nvue
uni_modules/uview-ui/components/u-datetime-picker/u-datetime-picker.vue

修改数据场景，从服务端获取时间后修改 DatetimePicker v-model 绑定的值，弹出的日期时间组件无法更新，仍然是初始化时使用的时间。

fix: DatetimePicker v-model 绑定异步设置无效；

---

uni_modules/uview-ui/components/u-tooltip/u-tooltip.vue

u-tooltip组件size参数没应用到text样式，修复size不生效的问题。
style增加`fontSize: $u.addUnit(size),`

fix(u-tooltip):修复size不生效的问题
